---
- name: Build DC1 Switch Configurations
  hosts: dc1_fabric
  tasks:
  
    - name: Generate Structured Variables per Device
      import_role:
        name: arista.avd.eos_designs
      vars:
        generate_cv_tags:
          topology_hints: true

    - name: Generate Intended Config and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen